// Code generated by go-swagger; DO NOT EDIT.

package election

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"goBully/models"
)

// NewElectionMessageParams creates a new ElectionMessageParams object
// no default values defined in spec.
func NewElectionMessageParams() ElectionMessageParams {

	return ElectionMessageParams{}
}

// ElectionMessageParams contains all the bound params for the election message operation
// typically these are obtained from a http.Request
//
// swagger:parameters electionMessage
type ElectionMessageParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*election algorithm - get a coordinator
	  Required: true
	  In: body
	*/
	Election *models.InformationElectionDTO
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewElectionMessageParams() beforehand.
func (o *ElectionMessageParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.InformationElectionDTO
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("election", "body"))
			} else {
				res = append(res, errors.NewParseError("election", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Election = &body
			}
		}
	} else {
		res = append(res, errors.Required("election", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
