// Code generated by go-swagger; DO NOT EDIT.

package election

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"goBully/models"
)

// ElectionMessageOKCode is the HTTP code returned for type ElectionMessageOK
const ElectionMessageOKCode int = 200

/*ElectionMessageOK successful operation

swagger:response electionMessageOK
*/
type ElectionMessageOK struct {

	/*
	  In: Body
	*/
	Payload *models.InformationElectionDTO `json:"body,omitempty"`
}

// NewElectionMessageOK creates ElectionMessageOK with default headers values
func NewElectionMessageOK() *ElectionMessageOK {

	return &ElectionMessageOK{}
}

// WithPayload adds the payload to the election message o k response
func (o *ElectionMessageOK) WithPayload(payload *models.InformationElectionDTO) *ElectionMessageOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the election message o k response
func (o *ElectionMessageOK) SetPayload(payload *models.InformationElectionDTO) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ElectionMessageOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ElectionMessageForbiddenCode is the HTTP code returned for type ElectionMessageForbidden
const ElectionMessageForbiddenCode int = 403

/*ElectionMessageForbidden operation not available

swagger:response electionMessageForbidden
*/
type ElectionMessageForbidden struct {
}

// NewElectionMessageForbidden creates ElectionMessageForbidden with default headers values
func NewElectionMessageForbidden() *ElectionMessageForbidden {

	return &ElectionMessageForbidden{}
}

// WriteResponse to the client
func (o *ElectionMessageForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// ElectionMessageNotFoundCode is the HTTP code returned for type ElectionMessageNotFound
const ElectionMessageNotFoundCode int = 404

/*ElectionMessageNotFound error in operation

swagger:response electionMessageNotFound
*/
type ElectionMessageNotFound struct {
}

// NewElectionMessageNotFound creates ElectionMessageNotFound with default headers values
func NewElectionMessageNotFound() *ElectionMessageNotFound {

	return &ElectionMessageNotFound{}
}

// WriteResponse to the client
func (o *ElectionMessageNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
