// Code generated by go-swagger; DO NOT EDIT.

package election

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"goBully/models"
)

// StartElectionMessageOKCode is the HTTP code returned for type StartElectionMessageOK
const StartElectionMessageOKCode int = 200

/*StartElectionMessageOK successful operation

swagger:response startElectionMessageOK
*/
type StartElectionMessageOK struct {

	/*
	  In: Body
	*/
	Payload *models.InformationElectionDTO `json:"body,omitempty"`
}

// NewStartElectionMessageOK creates StartElectionMessageOK with default headers values
func NewStartElectionMessageOK() *StartElectionMessageOK {

	return &StartElectionMessageOK{}
}

// WithPayload adds the payload to the start election message o k response
func (o *StartElectionMessageOK) WithPayload(payload *models.InformationElectionDTO) *StartElectionMessageOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the start election message o k response
func (o *StartElectionMessageOK) SetPayload(payload *models.InformationElectionDTO) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StartElectionMessageOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// StartElectionMessageForbiddenCode is the HTTP code returned for type StartElectionMessageForbidden
const StartElectionMessageForbiddenCode int = 403

/*StartElectionMessageForbidden operation not available

swagger:response startElectionMessageForbidden
*/
type StartElectionMessageForbidden struct {
}

// NewStartElectionMessageForbidden creates StartElectionMessageForbidden with default headers values
func NewStartElectionMessageForbidden() *StartElectionMessageForbidden {

	return &StartElectionMessageForbidden{}
}

// WriteResponse to the client
func (o *StartElectionMessageForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// StartElectionMessageNotFoundCode is the HTTP code returned for type StartElectionMessageNotFound
const StartElectionMessageNotFoundCode int = 404

/*StartElectionMessageNotFound error in operation

swagger:response startElectionMessageNotFound
*/
type StartElectionMessageNotFound struct {
}

// NewStartElectionMessageNotFound creates StartElectionMessageNotFound with default headers values
func NewStartElectionMessageNotFound() *StartElectionMessageNotFound {

	return &StartElectionMessageNotFound{}
}

// WriteResponse to the client
func (o *StartElectionMessageNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
