version: '2'

vars:
  CONTAINER: leonardpahlke/gobully:latest

tasks:

  build:
    desc: Build docker container
    cmds:
      - docker build -t {{.CONTAINER}} .
      - docker rmi $(docker images --filter "dangling=true" -q --no-trunc)

  run:
    desc: Start docker container
    cmds:
      - docker run --rm -itd -p 8080:8080 {{.CONTAINER}}
      - docker ps

  swagger:
    desc: Generate swagger.yml and start local server
    cmds:
      - swagger validate ./api/swagger.yml
      - swagger generate spec -o ./api/swagger.yml --scan-models
      - swagger serve ./api/swagger.yml

  szenario:
    deps: [build]
    desc: Start docker-compose scenario
    cmds:
      - echo TODO

  connect:
    deps: [build]
    desc: Connect to docker container
    cmds:
      - echo TODO

  update:
    desc: Update project dependencies
    cmds:
      - go list -e $(go list -m all)
      - go mod download