// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RegisterResponseDTO response object after register to id service
//
// swagger:model RegisterResponseDTO
type RegisterResponseDTO struct {

	// dummy message to print response
	// Required: true
	Message *string `json:"message"`

	// all registered users
	// Required: true
	UserIDInfos []*InformationUserDTO `json:"user_id_infos"`
}

// Validate validates this register response d t o
func (m *RegisterResponseDTO) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserIDInfos(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RegisterResponseDTO) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("message", "body", m.Message); err != nil {
		return err
	}

	return nil
}

func (m *RegisterResponseDTO) validateUserIDInfos(formats strfmt.Registry) error {

	if err := validate.Required("user_id_infos", "body", m.UserIDInfos); err != nil {
		return err
	}

	for i := 0; i < len(m.UserIDInfos); i++ {
		if swag.IsZero(m.UserIDInfos[i]) { // not required
			continue
		}

		if m.UserIDInfos[i] != nil {
			if err := m.UserIDInfos[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("user_id_infos" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *RegisterResponseDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RegisterResponseDTO) UnmarshalBinary(b []byte) error {
	var res RegisterResponseDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
