// Code generated by go-swagger; DO NOT EDIT.

package register

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gobully/models"
)

// RegisterServiceOKCode is the HTTP code returned for type RegisterServiceOK
const RegisterServiceOKCode int = 200

/*RegisterServiceOK successful operation

swagger:response registerServiceOK
*/
type RegisterServiceOK struct {

	/*
	  In: Body
	*/
	Payload *models.RegisterResponseDTO `json:"body,omitempty"`
}

// NewRegisterServiceOK creates RegisterServiceOK with default headers values
func NewRegisterServiceOK() *RegisterServiceOK {

	return &RegisterServiceOK{}
}

// WithPayload adds the payload to the register service o k response
func (o *RegisterServiceOK) WithPayload(payload *models.RegisterResponseDTO) *RegisterServiceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the register service o k response
func (o *RegisterServiceOK) SetPayload(payload *models.RegisterResponseDTO) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegisterServiceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RegisterServiceForbiddenCode is the HTTP code returned for type RegisterServiceForbidden
const RegisterServiceForbiddenCode int = 403

/*RegisterServiceForbidden operation not available

swagger:response registerServiceForbidden
*/
type RegisterServiceForbidden struct {
}

// NewRegisterServiceForbidden creates RegisterServiceForbidden with default headers values
func NewRegisterServiceForbidden() *RegisterServiceForbidden {

	return &RegisterServiceForbidden{}
}

// WriteResponse to the client
func (o *RegisterServiceForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// RegisterServiceNotFoundCode is the HTTP code returned for type RegisterServiceNotFound
const RegisterServiceNotFoundCode int = 404

/*RegisterServiceNotFound error in operation

swagger:response registerServiceNotFound
*/
type RegisterServiceNotFound struct {
}

// NewRegisterServiceNotFound creates RegisterServiceNotFound with default headers values
func NewRegisterServiceNotFound() *RegisterServiceNotFound {

	return &RegisterServiceNotFound{}
}

// WriteResponse to the client
func (o *RegisterServiceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
