// Code generated by go-swagger; DO NOT EDIT.

package register

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SendUnregisterToServicesHandlerFunc turns a function with the right signature into a send unregister to services handler
type SendUnregisterToServicesHandlerFunc func(SendUnregisterToServicesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SendUnregisterToServicesHandlerFunc) Handle(params SendUnregisterToServicesParams) middleware.Responder {
	return fn(params)
}

// SendUnregisterToServicesHandler interface for that can handle valid send unregister to services params
type SendUnregisterToServicesHandler interface {
	Handle(SendUnregisterToServicesParams) middleware.Responder
}

// NewSendUnregisterToServices creates a new http.Handler for the send unregister to services operation
func NewSendUnregisterToServices(ctx *middleware.Context, handler SendUnregisterToServicesHandler) *SendUnregisterToServices {
	return &SendUnregisterToServices{Context: ctx, Handler: handler}
}

/*SendUnregisterToServices swagger:route POST /sendunregister register sendUnregisterToServices

unregister yourself from other user service user lists

*/
type SendUnregisterToServices struct {
	Context *middleware.Context
	Handler SendUnregisterToServicesHandler
}

func (o *SendUnregisterToServices) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSendUnregisterToServicesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
