// Code generated by go-swagger; DO NOT EDIT.

package register

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// SendUnregisterToServicesOKCode is the HTTP code returned for type SendUnregisterToServicesOK
const SendUnregisterToServicesOKCode int = 200

/*SendUnregisterToServicesOK successful operation

swagger:response sendUnregisterToServicesOK
*/
type SendUnregisterToServicesOK struct {
}

// NewSendUnregisterToServicesOK creates SendUnregisterToServicesOK with default headers values
func NewSendUnregisterToServicesOK() *SendUnregisterToServicesOK {

	return &SendUnregisterToServicesOK{}
}

// WriteResponse to the client
func (o *SendUnregisterToServicesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// SendUnregisterToServicesForbiddenCode is the HTTP code returned for type SendUnregisterToServicesForbidden
const SendUnregisterToServicesForbiddenCode int = 403

/*SendUnregisterToServicesForbidden operation not available

swagger:response sendUnregisterToServicesForbidden
*/
type SendUnregisterToServicesForbidden struct {
}

// NewSendUnregisterToServicesForbidden creates SendUnregisterToServicesForbidden with default headers values
func NewSendUnregisterToServicesForbidden() *SendUnregisterToServicesForbidden {

	return &SendUnregisterToServicesForbidden{}
}

// WriteResponse to the client
func (o *SendUnregisterToServicesForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// SendUnregisterToServicesNotFoundCode is the HTTP code returned for type SendUnregisterToServicesNotFound
const SendUnregisterToServicesNotFoundCode int = 404

/*SendUnregisterToServicesNotFound error in operation

swagger:response sendUnregisterToServicesNotFound
*/
type SendUnregisterToServicesNotFound struct {
}

// NewSendUnregisterToServicesNotFound creates SendUnregisterToServicesNotFound with default headers values
func NewSendUnregisterToServicesNotFound() *SendUnregisterToServicesNotFound {

	return &SendUnregisterToServicesNotFound{}
}

// WriteResponse to the client
func (o *SendUnregisterToServicesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
