// Code generated by go-swagger; DO NOT EDIT.

package register

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// TriggerRegisterToServiceOKCode is the HTTP code returned for type TriggerRegisterToServiceOK
const TriggerRegisterToServiceOKCode int = 200

/*TriggerRegisterToServiceOK successful operation

swagger:response triggerRegisterToServiceOK
*/
type TriggerRegisterToServiceOK struct {
}

// NewTriggerRegisterToServiceOK creates TriggerRegisterToServiceOK with default headers values
func NewTriggerRegisterToServiceOK() *TriggerRegisterToServiceOK {

	return &TriggerRegisterToServiceOK{}
}

// WriteResponse to the client
func (o *TriggerRegisterToServiceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// TriggerRegisterToServiceForbiddenCode is the HTTP code returned for type TriggerRegisterToServiceForbidden
const TriggerRegisterToServiceForbiddenCode int = 403

/*TriggerRegisterToServiceForbidden operation not available

swagger:response triggerRegisterToServiceForbidden
*/
type TriggerRegisterToServiceForbidden struct {
}

// NewTriggerRegisterToServiceForbidden creates TriggerRegisterToServiceForbidden with default headers values
func NewTriggerRegisterToServiceForbidden() *TriggerRegisterToServiceForbidden {

	return &TriggerRegisterToServiceForbidden{}
}

// WriteResponse to the client
func (o *TriggerRegisterToServiceForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// TriggerRegisterToServiceNotFoundCode is the HTTP code returned for type TriggerRegisterToServiceNotFound
const TriggerRegisterToServiceNotFoundCode int = 404

/*TriggerRegisterToServiceNotFound error in operation

swagger:response triggerRegisterToServiceNotFound
*/
type TriggerRegisterToServiceNotFound struct {
}

// NewTriggerRegisterToServiceNotFound creates TriggerRegisterToServiceNotFound with default headers values
func NewTriggerRegisterToServiceNotFound() *TriggerRegisterToServiceNotFound {

	return &TriggerRegisterToServiceNotFound{}
}

// WriteResponse to the client
func (o *TriggerRegisterToServiceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
