// Code generated by go-swagger; DO NOT EDIT.

package register

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UnregisterFromServiceHandlerFunc turns a function with the right signature into a unregister from service handler
type UnregisterFromServiceHandlerFunc func(UnregisterFromServiceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UnregisterFromServiceHandlerFunc) Handle(params UnregisterFromServiceParams) middleware.Responder {
	return fn(params)
}

// UnregisterFromServiceHandler interface for that can handle valid unregister from service params
type UnregisterFromServiceHandler interface {
	Handle(UnregisterFromServiceParams) middleware.Responder
}

// NewUnregisterFromService creates a new http.Handler for the unregister from service operation
func NewUnregisterFromService(ctx *middleware.Context, handler UnregisterFromServiceHandler) *UnregisterFromService {
	return &UnregisterFromService{Context: ctx, Handler: handler}
}

/*UnregisterFromService swagger:route POST /unregister register unregisterFromService

unregister service from your user list

*/
type UnregisterFromService struct {
	Context *middleware.Context
	Handler UnregisterFromServiceHandler
}

func (o *UnregisterFromService) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUnregisterFromServiceParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
