// Code generated by go-swagger; DO NOT EDIT.

package register

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UnregisterFromServiceOKCode is the HTTP code returned for type UnregisterFromServiceOK
const UnregisterFromServiceOKCode int = 200

/*UnregisterFromServiceOK successful operation

swagger:response unregisterFromServiceOK
*/
type UnregisterFromServiceOK struct {
}

// NewUnregisterFromServiceOK creates UnregisterFromServiceOK with default headers values
func NewUnregisterFromServiceOK() *UnregisterFromServiceOK {

	return &UnregisterFromServiceOK{}
}

// WriteResponse to the client
func (o *UnregisterFromServiceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// UnregisterFromServiceForbiddenCode is the HTTP code returned for type UnregisterFromServiceForbidden
const UnregisterFromServiceForbiddenCode int = 403

/*UnregisterFromServiceForbidden operation not available

swagger:response unregisterFromServiceForbidden
*/
type UnregisterFromServiceForbidden struct {
}

// NewUnregisterFromServiceForbidden creates UnregisterFromServiceForbidden with default headers values
func NewUnregisterFromServiceForbidden() *UnregisterFromServiceForbidden {

	return &UnregisterFromServiceForbidden{}
}

// WriteResponse to the client
func (o *UnregisterFromServiceForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// UnregisterFromServiceNotFoundCode is the HTTP code returned for type UnregisterFromServiceNotFound
const UnregisterFromServiceNotFoundCode int = 404

/*UnregisterFromServiceNotFound error in operation

swagger:response unregisterFromServiceNotFound
*/
type UnregisterFromServiceNotFound struct {
}

// NewUnregisterFromServiceNotFound creates UnregisterFromServiceNotFound with default headers values
func NewUnregisterFromServiceNotFound() *UnregisterFromServiceNotFound {

	return &UnregisterFromServiceNotFound{}
}

// WriteResponse to the client
func (o *UnregisterFromServiceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
